pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Kick Starter
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://lee1maman.github.io/
# 2. URL of this page
url:              http://lee1maman.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           Kick Starter
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://bit.ly/VeinKickstarterDream 
  #
  # URL of a cover photo of your project
  cover_image:    http://computerrescueusa.com/images/BANNER3.jpg
  #
  # Use a one-liner to describe your project
  description:    VEIN: From A Dream
#
# 4. Your Twitter handle
twitter_handle:   Kick Starter
#
# 5. Your Google analytics ID (Optional)
google_analytics: UA-48251851-1
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
   Hey everybody! <br />
  I just want to take the time to thank you in advance for supporting my music and getting involved with the new album! This is a very special project for me, and by far, the most exciting! <br />
  Please jump on board and be part of my team with just three simple clicks! And when you arrive at my Kickstarter page, you can take it even further by pledging!<br>
  THANKS!
